"""
PDF Report Generator Service

Generates professional PDF reports for daily violation summaries,
using formatting and terminology tailored to the Hybrid AI (Sentry-Judge) System.
"""

import os
from datetime import date
from typing import List, Dict, Any

from config.settings import settings


class ReportGenerator:
    """
    Generates professional PDF reports from daily violation data.
    
    Report includes:
    - Header with date and summary
    - Violation statistics table
    - Hourly distribution chart
    - Verified Evidence Gallery with ROI crops and metadata
    """
    
    def __init__(self, output_dir: str = None):
        """
        Initialize report generator.
        
        Args:
            output_dir: Directory for output PDFs
        """
        self.output_dir = output_dir or settings.report_output_dir
        os.makedirs(self.output_dir, exist_ok=True)
    
    def generate_daily_report(
        self,
        report_date: date,
        violations: List,
        stats: Dict[str, Any]
    ) -> str:
        """
        Generate comprehensive PDF report for a given date.
        
        Args:
            report_date: Date for the report
            violations: List of Violation records
            stats: Pre-calculated statistics dict
            
        Returns:
            Path to generated PDF file
        """
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, 
                Image, Table, TableStyle, KeepTogether
            )
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.lib import colors
            
            # Generate filename
            pdf_filename = f"PPE_Violation_Report_{report_date.strftime('%Y-%m-%d')}.pdf"
            pdf_path = os.path.join(self.output_dir, pdf_filename)
            
            # Create document
            doc = SimpleDocTemplate(
                pdf_path, 
                pagesize=A4,
                rightMargin=inch*0.75, 
                leftMargin=inch*0.75,
                topMargin=inch*0.75, 
                bottomMargin=inch*0.75
            )
            story = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=20,
                textColor=colors.HexColor('#0f172a'),
                spaceAfter=5,
                alignment=1 # Center
            )
            
            subtitle_style = ParagraphStyle(
                'Subtitle',
                parent=styles['Normal'],
                fontSize=12,
                textColor=colors.HexColor('#475569'),
                spaceAfter=25,
                alignment=1 # Center
            )
            
            section_header = ParagraphStyle(
                'SectionHeader',
                parent=styles['Heading2'],
                fontSize=16,
                textColor=colors.HexColor('#1e40af'),
                spaceBefore=20,
                spaceAfter=10,
                borderPadding=5,
                borderWidth=1,
                borderColor=colors.HexColor('#e2e8f0'),
                borderRadius=3
            )

            evidence_text_style = ParagraphStyle(
                'EvidenceText',
                parent=styles['Normal'],
                fontSize=10,
                leading=14,
                textColor=colors.HexColor('#334155')
            )
            
            # === Title ===
            story.append(Paragraph("Construction Safety Monitoring with Hybrid AI Models<br/>for PPE Violation Detection", title_style))
            story.append(Paragraph(
                f"<b>Daily Audit Report</b> &mdash; {report_date.strftime('%B %d, %Y')}<br/>"
                "<i>Generated by Sentry-Judge Architecture</i>",
                subtitle_style
            ))
            
            # === Summary Table ===
            story.append(Paragraph("System Execution Summary", section_header))
            
            summary_data = [
                ["Metric", "Value"],
                ["Total Worker Tracking Sessions", str(stats.get('total_detections', 0))],
                ["Total Verified Violations", str(stats.get('total_violations', 0))],
                ["Overall Compliance Score", f"{stats.get('compliance_rate', 100.0):.1f}%"],
                ["Missing Helmet Occurrences", str(stats.get('no_helmet_count', 0))],
                ["Missing Vest Occurrences", str(stats.get('no_vest_count', 0))],
                ["Critical (Both Missing) Occurrences", str(stats.get('both_missing_count', 0))],
            ]
            
            summary_table = Table(summary_data, colWidths=[4*inch, 2*inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 0), (-1, 0), 10),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f8fafc'), colors.HexColor('#f1f5f9')])
            ]))
            
            story.append(summary_table)
            
            # === Hourly Chart ===
            chart_path = self._generate_hourly_chart(violations)
            if chart_path and os.path.exists(chart_path):
                story.append(Paragraph("Violation Frequency Timeline", section_header))
                story.append(Spacer(1, 0.1 * inch))
                story.append(Image(chart_path, width=6*inch, height=3*inch))
            
            # === Violation Details (Evidence Gallery) ===
            story.append(Paragraph("Verified Evidence Gallery", section_header))
            
            # OSHA mapping
            osha_map = {
                "no_helmet": "OSHA 1926.100 (Head Protection)",
                "no_vest": "OSHA 1926.28 (High-Visibility Vest)",
                "both_missing": "OSHA 1926.100 / 1926.28"
            }
            
            violation_list = [v for v in violations if not (v.has_helmet and v.has_vest)]
            # Prioritize violations that have annotated_image_path
            violation_list.sort(key=lambda x: 0 if x.annotated_image_path else 1)
            
            for i, violation in enumerate(violation_list[:10], 1):
                time_str = violation.timestamp.strftime('%H:%M:%S')
                vtype = violation.violation_type
                type_str = vtype.replace('_', ' ').title()
                osha_code = osha_map.get(vtype, "N/A")
                
                sentry_conf = f"{violation.detection_confidence:.2f}" if violation.detection_confidence else "N/A"
                path_taken = violation.decision_path
                
                # Format text block
                text_content = f"""
                <b>Incident #{i}</b><br/>
                <b>Time:</b> {time_str}<br/>
                <b>Location:</b> {violation.site_location}<br/>
                <b>Camera:</b> {violation.camera_id}<br/>
                <br/>
                <b>Violation:</b> <font color='red'>{type_str}</font><br/>
                <b>Regulation:</b> {osha_code}<br/>
                <br/>
                <b>System Diagnostics:</b><br/>
                • Sentry (YOLO) Confidence: {sentry_conf}<br/>
                • Execution Path: {path_taken}<br/>
                • Processing Time: {violation.processing_time_ms} ms<br/>
                """
                
                # Check for image
                img_flowable = None
                if violation.annotated_image_path and os.path.exists(violation.annotated_image_path):
                    try:
                        # Constrain image size
                        img = Image(violation.annotated_image_path)
                        aspect = img.imageWidth / img.imageHeight
                        img_h = 2.5 * inch
                        img_w = img_h * aspect
                        if img_w > 3.0 * inch:
                            img_w = 3.0 * inch
                            img_h = img_w / aspect
                        
                        img.drawWidth = img_w
                        img.drawHeight = img_h
                        img_flowable = img
                    except Exception:
                        pass
                
                if not img_flowable:
                    img_flowable = Paragraph("<i>[No Evidence Image]</i>", evidence_text_style)
                
                # Layout in a table (Image Left | Text Right)
                ev_table = Table(
                    [[img_flowable, Paragraph(text_content, evidence_text_style)]],
                    colWidths=[3.2*inch, 3.3*inch],
                    style=[
                        ('VALIGN', (0,0), (-1,-1), 'TOP'),
                        ('LEFTPADDING', (0,0), (-1,-1), 0),
                        ('BOTTOMPADDING', (0,0), (-1,-1), 15),
                    ]
                )
                
                story.append(KeepTogether(ev_table))
                story.append(Spacer(1, 0.1 * inch))
            
            # === Footer ===
            story.append(Spacer(1, 0.3 * inch))
            story.append(Paragraph(
                "<hr/><br/><i>Automated Audit Document &mdash; Intelligent PPE Monitoring System</i>",
                ParagraphStyle('Footer', parent=styles['Normal'], fontSize=9, textColor=colors.gray, alignment=1)
            ))
            
            # Build PDF
            doc.build(story)
            print(f"[OK] PDF generated: {pdf_path}")
            
            return pdf_path
            
        except ImportError as e:
            print(f"[WARN] ReportLab not available: {e}")
            return self._generate_text_report(report_date, violations, stats)
    
    def _generate_hourly_chart(self, violations: List) -> str:
        """Generate hourly violation distribution chart."""
        try:
            import matplotlib
            matplotlib.use('Agg')  # Non-GUI backend
            import matplotlib.pyplot as plt
            
            # Extract hours
            hours = [
                v.timestamp.hour 
                for v in violations 
                if not (v.has_helmet and v.has_vest)
            ]
            
            if not hours:
                return None
            
            plt.figure(figsize=(9, 4.5))
            plt.hist(hours, bins=24, range=(0, 24), edgecolor='white', color='#3b82f6', alpha=0.8)
            plt.xlabel('Hour of Day', fontsize=11, fontweight='bold', color='#334155')
            plt.ylabel('Recorded Occurrences', fontsize=11, fontweight='bold', color='#334155')
            plt.title('Daily Incident Distribution', fontsize=13, fontweight='bold', color='#0f172a', pad=15)
            plt.xticks(range(0, 24, 2))
            
            # Grid and styling
            plt.grid(axis='y', linestyle='--', alpha=0.4)
            plt.gca().spines['top'].set_visible(False)
            plt.gca().spines['right'].set_visible(False)
            plt.gca().spines['left'].set_color('#cbd5e1')
            plt.gca().spines['bottom'].set_color('#cbd5e1')
            
            chart_path = os.path.join(self.output_dir, 'hourly_chart.png')
            plt.savefig(chart_path, dpi=150, bbox_inches='tight', facecolor='#ffffff')
            plt.close()
            
            return chart_path
            
        except Exception as e:
            print(f"[WARN] Chart generation failed: {e}")
            return None
    
    def _generate_text_report(
        self,
        report_date: date,
        violations: List,
        stats: Dict[str, Any]
    ) -> str:
        """Fallback text report when PDF libraries unavailable."""
        filename = f"PPE_Report_{report_date.strftime('%Y-%m-%d')}.txt"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, "w") as f:
            f.write("=" * 60 + "\n")
            f.write("      PPE COMPLIANCE DAILY REPORT\n")
            f.write("=" * 60 + "\n\n")
            f.write(f"Date: {report_date.strftime('%B %d, %Y')}\n\n")
            f.write("-" * 40 + "\n")
            f.write("SUMMARY\n")
            f.write("-" * 40 + "\n")
            f.write(f"Total Detections:  {stats.get('total_detections', 0)}\n")
            f.write(f"Total Violations:  {stats.get('total_violations', 0)}\n")
            f.write(f"Compliance Rate:   {stats.get('compliance_rate', 100.0):.1f}%\n\n")
            f.write("-" * 40 + "\n")
            f.write("VIOLATION BREAKDOWN\n")
            f.write("-" * 40 + "\n")
            f.write(f"No Helmet:    {stats.get('no_helmet_count', 0)}\n")
            f.write(f"No Vest:      {stats.get('no_vest_count', 0)}\n")
            f.write(f"Both Missing: {stats.get('both_missing_count', 0)}\n\n")
            f.write("=" * 60 + "\n")
            f.write("Auto-generated by Intelligent PPE Detection System\n")
        
        return filepath
